import { Inter } from 'next/font/google';
import '../styles/sass/global.scss';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Universe Explorer',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={inter.className}>{children}</body>
		</html>
	);
}
