import Link from 'next/link';

export default function Home() {
	return (
		<main>
			<SolarSystem />
			<div className='container'>
				<Navigation />
				<div className='hero section'>
					<h1 className='text_centered'>Universe Explorer</h1>
					<h4>Generated by create next app</h4>
				</div>
			</div>
		</main>
	);
}

const Navigation = () => {
	return (
		<nav className='navigation'>
			<ul className='left'>
				<li>
					<Link href='/documentation' target='_blank'>
						Doc
					</Link>
				</li>
				<li>
					<Link href='https://github.com/SantiagoCode/UniverseExplorer' target='_blank'>
						Repo
					</Link>
				</li>
				<li>
					<Link href='/contact' target='_blank'>
						Contact
					</Link>
				</li>
			</ul>
			<ul className='right'>
				<li>
					<Link href='/login'>Login</Link>
				</li>
				<li>
					<Link href='/register'>Register</Link>
				</li>
			</ul>
		</nav>
	);
};

const SolarSystem = () => {
	return (
		<div className='solar_system_container'>
			<div className='solar_system'>
				<div className='sun'></div>
				<div className='mercury'></div>
				<div className='venus'></div>
				<div className='earth'></div>
				<div className='mars'></div>
				<div className='jupiter'></div>
				<div className='saturn'></div>
				<div className='uranus'></div>
				<div className='neptune'></div>
			</div>
		</div>
	);
};
