export default function Home() {
	return (
		<main>
			<div className='container'>
				<div className='hero section'>
					<h1 className='text_centered'>Universe Explorer</h1>
					<h4>Generated by create next app</h4>
				</div>
			</div>
		</main>
	);
}
